### ISSUE TITLE
NPM version not updated

### ISSUE THREAD

**Issue by MikelArnaiz** [jonkemp/useref#19]
Is there any reason why the NPM version is not updated to [the last commit](https://github.com/jonkemp/useref/commit/e3a9bf14980fefe609b6f745050b32e5dc843180)?

Last version available is 1.2.0 released on March 25, 2016. 
But I see the last commit is from April 6, 2017.

That commit fixes the issue an having with [loadCSS](https://github.com/filamentgroup/loadCSS), as I need to set a `link` to `rel="preload"`

**Comment by jonkemp** [comment]
No, no reason. It will be tonight before I can do it though. In the meantime, you can configure your local repo to pull the latest version from here if you need to.

**Comment by jonkemp** [comment]
Done.
