### ISSUE TITLE
jade support?

### ISSUE THREAD

**Issue by frenz1e** [jonkemp/useref#5]
It seems that this may be done quite simple, by just adding jade syntax in condition in refManager.js

```
<script src=""></script> to script(src="")
<link rel="stylesheet" href=""> to link(rel="stylesheet" href="")
```

and maybe some option for chose syntax(html/jade)

**Comment by jonkemp** [comment]
This is a fork (and I don't use Jade so I'm not sure) but there is a test for Jade support and it passes.

https://github.com/jonkemp/useref/blob/master/test/test.js#L223
